# Local dns configuration used by singbox itself
[[core.singbox.dns.servers]]
address = "8.8.8.8"
detour = "direct"
tag = "dns-local"

[[core.singbox.route.rules]]
action = "sniff"
inbound = [
  "dns-in",
]

[[core.singbox.route.rules]]
action = "hijack-dns"
inbound = [
  "dns-in",
]

[[core.singbox.route.rules]]
action = "hijack-dns"
protocol = "dns"
