version: 2

before:
  hooks:
    - go mod download
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    ldflags: "-s -w"
    goarch:
      - amd64

  - id: slim
    goos:
      - linux
    goarch:
      - amd64
    ldflags: "-s -w"
    binary: junction
    skip: "archive"

dockers:
  - image_templates:
      - "ghcr.io/fmotalleb/junction:{{ .Version }}-slim"
      - "ghcr.io/fmotalleb/junction:latest-slim"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - slim
    extra_files:
      - docker
    build_flag_templates:
      - "--target=slim"
    use: buildx

archives:
  - id: default
    builds:
      - default

release:
  github:
    owner: FMotalleb
    name: crontab-go
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append

changelog:
  disable: true
