version: 2

before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    goos:
      - darwin
      - linux
      - windows
    tags:
      - with_utls
    goarch:
      - amd64

  - id: slim
    env:
      - CGO_ENABLED=0
    tags:
      - with_utls
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"
    goos:
      - linux
    goarch:
      - amd64
    binary: junction
    skip: "archive"

dockers_v2:
  - id: junction-vless
    sbom: false
    platforms:
      - linux/amd64
    images:
      - ghcr.io/fmotalleb/junction
    tags:
      - "{{ .Version }}-vless"
      - latest-vless
    labels:
      "org.opencontainers.image.description": "Junction (VLESS Support)"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    ids:
      - slim
    flags:
      - --target=slim
    extra_files:
      - docker

  - id: junction
    sbom: false
    platforms:
      - linux/amd64
    images:
      - ghcr.io/fmotalleb/junction
    tags:
      - "{{ .Version }}-distroless"
      - latest-distroless
      - latest
    labels:
      "org.opencontainers.image.description": "Junction"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    ids:
      - slim
    flags:
      - --target=distroless
    extra_files:
      - docker

release:
  github:
    owner: fmotalleb
    name: junction
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append

changelog:
  disable: true
