version: 2

before:
  hooks:
    - go mod download
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/FMotalleb/junction/git.version={{.Version}}"
      - "-X github.com/FMotalleb/junction/git.commit={{.ShortCommit}}"
      - "-X github.com/FMotalleb/junction/git.date={{.Date}}"
      - "-X github.com/FMotalleb/junction/git.branch={{.Branch}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

  - id: slim
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/FMotalleb/junction/git.version={{.Version}}"
      - "-X github.com/FMotalleb/junction/git.commit={{.ShortCommit}}"
      - "-X github.com/FMotalleb/junction/git.date={{.Date}}"
      - "-X github.com/FMotalleb/junction/git.branch={{.Branch}}"
    goos:
      - windows
      # - linux
    goarch:
      - amd64
    binary: junction
    skip: "archive"

dockers:
  - image_templates:
      - "ghcr.io/fmotalleb/junction:{{ .Version }}-slim"
      - "ghcr.io/fmotalleb/junction:latest-slim"
      - "ghcr.io/fmotalleb/junction:{{ .Version }}"
      - "ghcr.io/fmotalleb/junction:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - slim
    extra_files:
      - docker
    build_flag_templates:
      - "--target=slim"
    use: buildx

archives:
  - id: default
    builds:
      - default

release:
  github:
    owner: FMotalleb
    name: junction
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append

changelog:
  disable: true
