services:
  junction:
    build:
      context: .
      dockerfile: docker/Dockerfile
      no_cache: true
    volumes:
      - "./docker/root/docker-entrypoint.sh:/docker-entrypoint.sh"
      - "./ssl:/etc/ssl/"
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
