services:
  junction:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - "./docker/root/docker-entrypoint.sh:/docker-entrypoint.sh"
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
