services:
  junction:
    image: docker.dornica-co.local/fmotalleb/junction:0.6.4-distroless
    command:
      - run
      - --routing=tcp-raw
      - --listen=0.0.0.0:443
      - --target=172.16.17.23:80
      - --timeout=2s
      - --debug
    ports:
      - 7892:6980
      - 80:80
      - 443:443
    environment:
      - ZAPLOG_LEVEL=debug
    env_file:
      - .env
  openvpn:
    profiles:
      - "ovpn"
    image: ghcr.io/fmotalleb/openvpn-client:v0.1.0
    command: ["-D"]
    restart: unless-stopped
    cap_add:
      - net_admin
    network_mode: "service:junction"
    volumes:
      # text file,
      #   first line = username
      #   second line = password
      #<Username>
      #<Password>
      - ./vpn.secret.auth:/vpn/vpn.auth
      # OpenVpn config file
      - ./vpn.secret.conf:/vpn/vpn.conf

  # dns:
  #   image: fmotalleb/cord-locator:v2.0.11
  #   ports:
  #     - 53:53/udp
  #   configs:
  #     - source: cord-locator
  #       target: /app/config.yaml
