[[entrypoints]]
routing = "sni" # SNI routing detects its host
proxy = "socks5://10.11.12.22:8999" # Proxy address
to = "443" # Explicit sni target port declaration (default 443)
port = 8443 # listen port
timeout = "50s" # Timeout for connection that are made in this entrypoint (default to `TIMEOUT` env var or 24Hours)

[[entrypoints]]
routing = "http-header" # SNI routing detects its host
proxy = [ # Proxy chain using array
  "socks5://10.11.12.22:8999", # Connects to this
  "socks5://10.11.12.22:8998" # Then using that connection connects to this
]
to = "80" # Explicit http target port declaration (default 80)
port = 8080

[[entrypoints]]
routing = "http-header" # SNI routing detects its host
proxy = [
  "ssh://test:password@test2:22", # SSH proxy using username:password
  "ssh://test@test2:22/path/to/private/key" # SSH proxy using username:private/public key authentication
]
port = 8090

[[entrypoints]]
routing = "tcp-raw"
proxy = "socks5://10.11.12.22:8999,ssh://test@test2:22" # Proxy chain using string with `,` separator
to = "192.168.200.56:8469" # tcp-raw routing is unable to detect its target host thus it needs target's ip:port
port = 8444
timeout = "50s"
