include = [
  "/etc/junction/*.d/*",
]

[[entrypoints]]
routing = "sni"
listen = "0.0.0.0:${SNI_PORT:-443}"
to = "443"
proxy = "socks5://127.0.0.1:6980"

[[entrypoints]]
routing = "http-header"
listen = "0.0.0.0:${HTTP_PORT:-80}"
to = "80"
proxy = "socks5://127.0.0.1:6980"
