name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6 # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6 # v6.2.0
        with:
          go-version: "1.26"
          check-latest: true
      - name: Setup Node.js
        # Pin to the latest v4 commit used at the time of writing
        uses: actions/setup-node@v4 # v4.0.2
        with:
          node-version: 20
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go install github.com/goreleaser/goreleaser/v2@latest 
          goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dist
        uses: actions/upload-artifact@v6 # v6.0.0
        with:
          name: dist
          path: dist
